<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-NKQ7MKH" failures="4" tests="4" name="Test(failed)(failed)(failed)(failed)" time="0.231" errors="0" timestamp="2023-11-10T16:48:51 IST">
  <testcase classname="TestNG_Failed_Suite.Ex_1_Failedtest1" name="TC1" time="0.044">
    <failure type="java.lang.AssertionError" message="Failed: Results are not same expected [Akash] but found [Shyam]">
      <![CDATA[java.lang.AssertionError: Failed: Results are not same expected [Akash] but found [Shyam]
at TestNG_Failed_Suite.Ex_1_Failedtest1.TC1(Ex_1_Failedtest1.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TC1 -->
  <testcase classname="TestNG_Failed_Suite.Ex_1_Failedtest1" name="TC2" time="0.014">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at TestNG_Failed_Suite.Ex_1_Failedtest1.TC2(Ex_1_Failedtest1.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase classname="TestNG_Failed_Suite.Ex_2_Failedtest2" name="TC2" time="0.003">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at TestNG_Failed_Suite.Ex_2_Failedtest2.TC2(Ex_2_Failedtest2.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase classname="TestNG_Failed_Suite.Ex_2_Failedtest2" name="TC1" time="0.004">
    <failure type="java.lang.AssertionError" message="Failed: Results are not same did not expect [Shyam] but found [Shyam]">
      <![CDATA[java.lang.AssertionError: Failed: Results are not same did not expect [Shyam] but found [Shyam]
at TestNG_Failed_Suite.Ex_2_Failedtest2.TC1(Ex_2_Failedtest2.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC1 -->
  <testcase classname="TestNG_Failed_Suite.Ex_1_Failedtest1" name="TC3" time="0.0">
    <ignored/>
  </testcase> <!-- TC3 -->
  <testcase classname="TestNG_Failed_Suite.Ex_2_Failedtest2" name="TC3" time="0.0">
    <ignored/>
  </testcase> <!-- TC3 -->
</testsuite> <!-- Test(failed)(failed)(failed)(failed) -->
