<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NKQ7MKH" failures="0" tests="4" name="TestNG_Keywords.Ex_4_timeOut" time="5.067" errors="1" timestamp="2023-11-07T10:49:03 IST" skipped="0">
  <testcase classname="TestNG_Keywords.Ex_4_timeOut" name="TC2" time="0.015">
    <system-out>
      <![CDATA[Running TC2
Running TC2
Running TC2
Running TC2]]>
    </system-out>
  </testcase> <!-- TC2 -->
  <testcase classname="TestNG_Keywords.Ex_4_timeOut" name="TC1" time="5.037">
    <error message="Method TestNG_Keywords.Ex_4_timeOut.TC1() didn&#039;t finish within the time-out 5000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNG_Keywords.Ex_4_timeOut.TC1() didn't finish within the time-out 5000
at java.base@17.0.5/java.lang.Thread.sleep(Native Method)
at app//TestNG_Keywords.Ex_4_timeOut.TC1(Ex_4_timeOut.java:11)
at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- TC1 -->
  <testcase classname="TestNG_Keywords.Ex_4_timeOut" name="TC3" time="0.011">
    <system-out>
      <![CDATA[Running TC3]]>
    </system-out>
  </testcase> <!-- TC3 -->
  <testcase classname="TestNG_Keywords.Ex_4_timeOut" name="TC4" time="0.004">
    <system-out>
      <![CDATA[Running TC4]]>
    </system-out>
  </testcase> <!-- TC4 -->
  <system-out>
    <![CDATA[Running TC2
Running TC2
Running TC2
Running TC2
Running TC3
Running TC4]]>
  </system-out>
</testsuite> <!-- TestNG_Keywords.Ex_4_timeOut -->
